#!/bin/bash
set -e

if [[ ! -n $(which swig) ]]; then
    echo "swig must be installed";
    exit 1
fi

if [[ $# -ge 1 ]]; then
    BUILD_DIR=$1
fi

if [[ -z ENABLE_TESTNET ]]; then
    DEPS_BUILD='deps/build-testnet'
else
    DEPS_BUILD='deps/build'
fi

BASE=$(pwd)
CORE_PATH="$BASE/../airbitz-core"
BUILD_PATH=${BUILD_DIR:-$CORE_PATH/$DEPS_BUILD}
WALLET_PATH="$BASE/library/src/main"

# Copy the core build output into the jni folder:
mkdir -p $WALLET_PATH/jni/
mkdir -p $WALLET_PATH/jni/armeabi
mkdir -p $WALLET_PATH/jni/x86
cp $CORE_PATH/src/ABC.h $WALLET_PATH/jni/
sed  -e 's/const char *\*/const char *const /' $WALLET_PATH/jni/ABC.h \
    > $WALLET_PATH/jni/ABC-const.h
cp $BUILD_PATH/abc/android-arm/libabc.so $WALLET_PATH/jni/armeabi/libabc.so
cp $BUILD_PATH/abc/android-x86/libabc.so $WALLET_PATH/jni/x86/libabc.so

# Generate the wrapper code:
cd $WALLET_PATH
swig -java -package co.airbitz.internal \
    -outdir java/co/airbitz/internal -o jni/ABC_wrap.c jni/ABC.i

# Build the wrapper library:
cd $WALLET_PATH/jni/
$BUILD_PATH/ndk/android-ndk-r10d/ndk-build

# Gradle is looking in the wrong place for libraries:
cp -R $WALLET_PATH/libs/* $WALLET_PATH/jniLibs
