#!/bin/bash

# Pick up the current directory:
BASE=$(pwd)
export BUILD_DIR=${BUILD_DIR:-$BASE/../airbitz-core/deps/build}

# Testnet options:
if [ "${1-}" = "testnet" ]; then
    shift
    export BUILD_DIR=${BUILD_DIR}-testnet
    export ENABLE_TESTNET=1
fi

# Build the core:
cd $BASE/../airbitz-core/deps
touch recipes/abc/abc.recipe
make abc.build-android-arm abc.build-android-x86 $@

# Now build the JNI wrapper:
cd $BASE
./cpabc
